Repository jakethedog104/SimplyPluralWatch, pull requests merged in 2025-03, with the labels that each got.

#5 Doc Update
  README.md
  screenshots/sample_alter.png
  screenshots/sample_custom.png
  screenshots/sample_greeting.png
Labels: documentation

#6 Update README.md
  README.md
  screenshots/sample_alter.png
Labels: documentation

#7 Fix #1 & Add Icon
  README.md
  app/src/main/res/drawable/splash_icon.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
  app/src/main/res/play_store_512.png
Labels: documentation, enhancement

#10 cleanup alter front conversion
  app/src/main/java/com/example/simplypluralwatch/presentation/SimplyPlural.kt
  app/src/test/java/presentation/AlterTest.kt
Labels: bug

#11 Front history
  app/src/main/java/com/example/simplypluralwatch/presentation/MainActivity.kt
  app/src/main/java/com/example/simplypluralwatch/presentation/SimplyPlural.kt
  app/src/test/java/presentation/SimplyPluralTest.kt
Labels: enhancement

#14 Hide archived members
  app/src/main/java/com/example/simplypluralwatch/presentation/SimplyPlural.kt
Labels: enhancement

#16 reload front/alters/custom on refresh
  app/src/main/java/com/example/simplypluralwatch/presentation/MainActivity.kt
  app/src/main/java/com/example/simplypluralwatch/presentation/SimplyPlural.kt
Labels: bug
